fix: `MapIterator` does not support `filter` on some platforms
```log
error TS2339: Property 'filter' does not exist on type 'MapIterator<[string, number]>'.
```